### ISSUE TITLE
graft

### ISSUE THREAD

**Issue by amirhnajafiz** [amirhnajafiz/graft#2]
## Proposal

I want to implement the RAFT protocol using Go.

### Config file

```yaml
nodes:
  - localhost:8080
  - localhost:8081
leader_election_timeout: 5 # in seconds
heartbeat_interval: 10 # in seconds
clocks_limit: 30 # in seconds
```
